=begin
#speechapi

#Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveVoiceRecognitionApiClient::TextToSpeechRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TextToSpeechRequest' do
  before do
    # run before each test
    @instance = CloudmersiveVoiceRecognitionApiClient::TextToSpeechRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TextToSpeechRequest' do
    it 'should create an instance of TextToSpeechRequest' do
      expect(@instance).to be_instance_of(CloudmersiveVoiceRecognitionApiClient::TextToSpeechRequest)
    end
  end
  describe 'test attribute "format"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "text"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
