=begin
#speechapi

#Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveVoiceRecognitionApiClient::RecognizeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RecognizeApi' do
  before do
    # run before each test
    @instance = CloudmersiveVoiceRecognitionApiClient::RecognizeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecognizeApi' do
    it 'should create an instance of RecognizeApi' do
      expect(@instance).to be_instance_of(CloudmersiveVoiceRecognitionApiClient::RecognizeApi)
    end
  end

  # unit tests for recognize_file
  # Recognize audio input as text using machine learning
  # Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
  # @param speech_file Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.
  # @param [Hash] opts the optional parameters
  # @return [SpeechRecognitionResult]
  describe 'recognize_file test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
