=begin
#speechapi

#Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-voice-recognition-api-client/api_client'
require 'cloudmersive-voice-recognition-api-client/api_error'
require 'cloudmersive-voice-recognition-api-client/version'
require 'cloudmersive-voice-recognition-api-client/configuration'

# Models
require 'cloudmersive-voice-recognition-api-client/models/speech_recognition_result'
require 'cloudmersive-voice-recognition-api-client/models/text_to_speech_request'

# APIs
require 'cloudmersive-voice-recognition-api-client/api/recognize_api'
require 'cloudmersive-voice-recognition-api-client/api/speak_api'

module CloudmersiveVoiceRecognitionApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveVoiceRecognitionApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
